version: '2.3'

services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - "docker-compose-env/main.env"
      - "docker-compose-env/postgres.env"
      - "docker-compose-env/rabbitmq.env"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./web-data:/workspace/media
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - "docker-compose-env/postgres.env"
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    env_file:
      - "docker-compose-env/rabbitmq.env"
    expose:
      - "5672"
      - "15672"
