version: '2.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "${COMPOSE_PROJECT_NAME}"
    container_name: "${WEB_CONTAINER_NAME}"
    restart: always
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - "./docker/django.env"
      - "./docker/postgres.env"
      - "./docker/rabbitmq.env"
    ports:
      - "${WEB_EXTERNAL_PORT}:8000"
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - "./docker/postgres.env"
    expose:
      - "5432"

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    env_file:
      - "./docker/rabbitmq.env"
    expose:
      - "5672"
      - "15672"
