version: '2.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "${COMPOSE_PROJECT_NAME}"
    container_name: "${WEB_CONTAINER_NAME}"
    restart: always
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ".env.django"
      - ".env.postgres"
      - ".env.rabbitmq"
    ports:
      - "${WEB_EXTERNAL_PORT}:8000"
    volumes:
      - ./web-data:/workspace/media
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ".env.postgres"
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    env_file:
      - ".env.rabbitmq"
    expose:
      - "5672"
      - "15672"
